# NFL Combine Data Cleaning and Organization

This notebook focuses on one goal:

**Create one clean, organized combine dataset that can later be used in the master dataset.**

The notebook keeps the cleaning simple and conservative:
- load the raw file
- inspect the data
- clean column names
- clean basic text formatting
- check duplicates
- check missing values
- organize the final columns
- save one cleaned dataset

In [19]:
import pandas as pd

# Show more columns when printing dataframes
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

## 1. Load the raw dataset

In [20]:
df = pd.read_csv("NFL_Combine_Since_2000.csv")

print("Rows, Columns:", df.shape)
df.head()

Rows, Columns: (8649, 15)

,Player,Position,School,Height,Weight,40-yd Dash,Vertical Jump,Bench Press,Broad Jump,3-Cone Drill,20-yd Shuttle,Team,Round,Pick,Year
0,Xavier Worthy,WR,Texas,71.0,165.0,4.21,41.0,NaN,131.0,NaN,NaN,Kansas City Chiefs,1.0,28.0,2024
1,Donte' Stallworth,WR,Tennessee,72.0,197.0,4.22,NaN,NaN,NaN,NaN,NaN,New Orleans Saints,1.0,13.0,2002
2,John Ross,WR,Washington,71.0,188.0,4.22,37.0,NaN,133.0,NaN,NaN,Cincinnati Bengals,1.0,9.0,2017
3,Kalon Barnes,CB,Baylor,72.0,183.0,4.23,NaN,NaN,NaN,NaN,NaN,Carolina Panthers,7.0,242.0,2022
4,Chris Johnson,RB,East Carolina,71.0,197.0,4.24,35.0,NaN,130.0,NaN,NaN,Tennessee Titans,1.0,24.0,2008

## 2. Inspect the raw data

This helps us understand what is in the file before making changes.

In [21]:
print("Column names:")
print(df.columns.tolist())

print()
print("Data types:")
print(df.dtypes)

Column names:
['Player', 'Position', 'School', 'Height', 'Weight', '40-yd Dash', 'Vertical Jump', 'Bench Press', 'Broad Jump', '3-Cone Drill', '20-yd Shuttle', 'Team', 'Round', 'Pick', 'Year']

Data types:
Player            object
Position          object
School            object
Height           float64
Weight           float64
40-yd Dash       float64
Vertical Jump    float64
Bench Press      float64
Broad Jump       float64
3-Cone Drill     float64
20-yd Shuttle    float64
Team              object
Round            float64
Pick             float64
Year               int64
dtype: object

In [22]:
print("First 10 rows:")
df.head(10)

First 10 rows:

,Player,Position,School,Height,Weight,40-yd Dash,Vertical Jump,Bench Press,Broad Jump,3-Cone Drill,20-yd Shuttle,Team,Round,Pick,Year
0,Xavier Worthy,WR,Texas,71.0,165.0,4.21,41.0,NaN,131.0,NaN,NaN,Kansas City Chiefs,1.0,28.0,2024
1,Donte' Stallworth,WR,Tennessee,72.0,197.0,4.22,NaN,NaN,NaN,NaN,NaN,New Orleans Saints,1.0,13.0,2002
2,John Ross,WR,Washington,71.0,188.0,4.22,37.0,NaN,133.0,NaN,NaN,Cincinnati Bengals,1.0,9.0,2017
3,Kalon Barnes,CB,Baylor,72.0,183.0,4.23,NaN,NaN,NaN,NaN,NaN,Carolina Panthers,7.0,242.0,2022
4,Chris Johnson,RB,East Carolina,71.0,197.0,4.24,35.0,NaN,130.0,NaN,NaN,Tennessee Titans,1.0,24.0,2008
5,Dri Archer,WR,Kent State,68.0,173.0,4.26,38.0,20.0,122.0,6.86,4.06,Pittsburgh Steelers,3.0,97.0,2014
6,Tariq Woolen,CB,Texas-San Antonio,76.0,205.0,4.26,42.0,NaN,NaN,NaN,NaN,Seattle Seahawks,5.0,153.0,2022
7,DJ Turner,CB,Michigan,71.0,178.0,4.26,38.5,NaN,131.0,NaN,NaN,Cincinnati Bengals,2.0,60.0,2023
8,Stanford Routt,CB,Houston,73.0,193.0,4.27,36.5,NaN,129.0,6.63,3.90,Oakland Raiders,2.0,38.0,2005
9,Marquise Goodwin,WR,Texas,69.0,183.0,4.27,NaN,13.0,132.0,NaN,NaN,Buffalo Bills,3.0,78.0,2013

## 3. Make a working copy and rename columns

We keep the raw dataframe unchanged and clean a copy.
The new column names are easier to read and easier to use later.

In [23]:
clean_df = df.copy()

clean_df = clean_df.rename(columns={
    "Player": "player",
    "Position": "position",
    "School": "school",
    "Height": "height_in",
    "Weight": "weight_lb",
    "40-yd Dash": "forty_yd_dash",
    "Vertical Jump": "vertical_jump",
    "Bench Press": "bench_press",
    "Broad Jump": "broad_jump",
    "3-Cone Drill": "three_cone_drill",
    "20-yd Shuttle": "twenty_yd_shuttle",
    "Team": "team",
    "Round": "round",
    "Pick": "pick",
    "Year": "year"
})

clean_df.head()

,player,position,school,height_in,weight_lb,forty_yd_dash,vertical_jump,bench_press,broad_jump,three_cone_drill,twenty_yd_shuttle,team,round,pick,year
0,Xavier Worthy,WR,Texas,71.0,165.0,4.21,41.0,NaN,131.0,NaN,NaN,Kansas City Chiefs,1.0,28.0,2024
1,Donte' Stallworth,WR,Tennessee,72.0,197.0,4.22,NaN,NaN,NaN,NaN,NaN,New Orleans Saints,1.0,13.0,2002
2,John Ross,WR,Washington,71.0,188.0,4.22,37.0,NaN,133.0,NaN,NaN,Cincinnati Bengals,1.0,9.0,2017
3,Kalon Barnes,CB,Baylor,72.0,183.0,4.23,NaN,NaN,NaN,NaN,NaN,Carolina Panthers,7.0,242.0,2022
4,Chris Johnson,RB,East Carolina,71.0,197.0,4.24,35.0,NaN,130.0,NaN,NaN,Tennessee Titans,1.0,24.0,2008

## 4. Clean basic text formatting

This step only does light cleaning:
- remove leading and trailing spaces
- keep text columns consistent
- keep original football labels and meaning

In [24]:
text_cols = ["player", "position", "school", "team"]

for col in text_cols:
    clean_df[col] = clean_df[col].astype("string").str.strip()

clean_df[["player", "position", "school", "team"]].head()

              player position         school                team
0      Xavier Worthy       WR          Texas  Kansas City Chiefs
1  Donte' Stallworth       WR      Tennessee  New Orleans Saints
2          John Ross       WR     Washington  Cincinnati Bengals
3       Kalon Barnes       CB         Baylor   Carolina Panthers
4      Chris Johnson       RB  East Carolina    Tennessee Titans

## 5. Check for duplicates

We check:
1. exact duplicate rows
2. duplicate records based on a more realistic combine key

For combine data, a safer key is:
- player
- year
- position
- school

In [25]:
# Exact duplicate rows
exact_duplicates = clean_df.duplicated().sum()
print("Exact duplicate rows:", exact_duplicates)

# Duplicate records using a more realistic combine key
key_cols = ["player", "year", "position", "school"]
key_duplicates = clean_df.duplicated(subset=key_cols).sum()
print("Duplicate rows using player-year-position-school:", key_duplicates)

Exact duplicate rows: 0
Duplicate rows using player-year-position-school: 0

In [26]:
# Show any duplicate records based on the combine key
duplicate_rows = clean_df[clean_df.duplicated(subset=key_cols, keep=False)].sort_values(key_cols)

duplicate_rows.head(20)

Empty DataFrame
Columns: [player, position, school, height_in, weight_lb, forty_yd_dash, vertical_jump, bench_press, broad_jump, three_cone_drill, twenty_yd_shuttle, team, round, pick, year]
Index: []

## 6. Check missing values

This tells us which columns are complete and which ones need attention later.
We are only inspecting missing values here, not filling them in.

In [27]:
missing_summary = pd.DataFrame({
    "missing_count": clean_df.isna().sum(),
    "missing_percent": (clean_df.isna().mean() * 100).round(2)
}).sort_values("missing_percent", ascending=False)

missing_summary

                   missing_count  missing_percent
three_cone_drill            3626            41.92
twenty_yd_shuttle           3481            40.25
bench_press                 3313            38.31
team                        3094            35.77
pick                        3094            35.77
round                       3094            35.77
broad_jump                  2145            24.80
vertical_jump               2049            23.69
forty_yd_dash                799             9.24
height_in                     29             0.34
weight_lb                     24             0.28
position                       0             0.00
player                         0             0.00
school                         0             0.00
year                           0             0.00

## 7. Quick value checks

These checks help us catch obvious issues without overcomplicating the notebook.

In [28]:
print("Year range:", clean_df["year"].min(), "to", clean_df["year"].max())
print("Unique positions:", clean_df["position"].nunique())
print("Unique schools:", clean_df["school"].nunique())

Year range: 2000 to 2025
Unique positions: 25
Unique schools: 356

In [29]:
numeric_cols = [
    "height_in", "weight_lb", "forty_yd_dash", "vertical_jump",
    "bench_press", "broad_jump", "three_cone_drill", "twenty_yd_shuttle",
    "round", "pick", "year"
]

clean_df[numeric_cols].describe().T

                    count         mean        std      min      25%      50%      75%      max
height_in          8620.0    73.829118   2.652721    64.00    72.00    74.00    76.00    82.00
weight_lb          8625.0   242.611130  45.601708   144.00   205.00   232.00   281.00   384.00
forty_yd_dash      7850.0     4.769701   0.304819     4.21     4.53     4.68     4.97     6.05
vertical_jump      6600.0    33.000879   4.208870    17.50    30.00    33.00    36.00    46.50
bench_press        5336.0    20.729573   6.338954     2.00    16.00    21.00    25.00    49.00
broad_jump         6504.0   115.001076   9.368291    74.00   109.00   116.00   122.00   147.00
three_cone_drill   5023.0     7.284784   0.416139     6.28     6.98     7.19     7.54     9.12
twenty_yd_shuttle  5168.0     4.402175   0.266326     3.73     4.21     4.36     4.56     5.56
round              5555.0     3.861566   1.938770     1.00     2.00     4.00     5.00     7.00
pick               5555.0   115.634743  70.893617     1.00    55.00   111.00   172.00   262.00
year               8649.0  2012.660654   7.490257  2000.00  2006.00  2013.00  2019.00  2025.00

## 8. Organize the final cleaned dataset

We keep the columns in a clean order so the dataset is easier to read and easier to merge later.
We are not creating extra derived columns here.

In [30]:
final_columns = [
    "player",
    "year",
    "position",
    "school",
    "height_in",
    "weight_lb",
    "forty_yd_dash",
    "vertical_jump",
    "bench_press",
    "broad_jump",
    "three_cone_drill",
    "twenty_yd_shuttle",
    "team",
    "round",
    "pick"
]

combine_clean = clean_df[final_columns].copy()
combine_clean.head()

,player,year,position,school,height_in,weight_lb,forty_yd_dash,vertical_jump,bench_press,broad_jump,three_cone_drill,twenty_yd_shuttle,team,round,pick
0,Xavier Worthy,2024,WR,Texas,71.0,165.0,4.21,41.0,NaN,131.0,NaN,NaN,Kansas City Chiefs,1.0,28.0
1,Donte' Stallworth,2002,WR,Tennessee,72.0,197.0,4.22,NaN,NaN,NaN,NaN,NaN,New Orleans Saints,1.0,13.0
2,John Ross,2017,WR,Washington,71.0,188.0,4.22,37.0,NaN,133.0,NaN,NaN,Cincinnati Bengals,1.0,9.0
3,Kalon Barnes,2022,CB,Baylor,72.0,183.0,4.23,NaN,NaN,NaN,NaN,NaN,Carolina Panthers,7.0,242.0
4,Chris Johnson,2008,RB,East Carolina,71.0,197.0,4.24,35.0,NaN,130.0,NaN,NaN,Tennessee Titans,1.0,24.0

## 9. Final review

A last look at the cleaned table before saving it.

In [31]:
print("Final shape:", combine_clean.shape)
combine_clean.info()

Final shape: (8649, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8649 entries, 0 to 8648
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   player             8649 non-null   string
 1   year               8649 non-null   int64
 2   position           8649 non-null   string
 3   school             8649 non-null   string
 4   height_in          8620 non-null   float64
 5   weight_lb          8625 non-null   float64
 6   forty_yd_dash      7850 non-null   float64
 7   vertical_jump      6600 non-null   float64
 8   bench_press        5336 non-null   float64
 9   broad_jump         6504 non-null   float64
 10  three_cone_drill   5023 non-null   float64
 11  twenty_yd_shuttle  5168 non-null   float64
 12  team               5555 non-null   string
 13  round              5555 non-null   float64
 14  pick               5555 non-null   float64
dtypes: float64(10), int64(1), string(4)
memory usage: 1013.7 KB

In [32]:
combine_clean.head(10)

,player,year,position,school,height_in,weight_lb,forty_yd_dash,vertical_jump,bench_press,broad_jump,three_cone_drill,twenty_yd_shuttle,team,round,pick
0,Xavier Worthy,2024,WR,Texas,71.0,165.0,4.21,41.0,NaN,131.0,NaN,NaN,Kansas City Chiefs,1.0,28.0
1,Donte' Stallworth,2002,WR,Tennessee,72.0,197.0,4.22,NaN,NaN,NaN,NaN,NaN,New Orleans Saints,1.0,13.0
2,John Ross,2017,WR,Washington,71.0,188.0,4.22,37.0,NaN,133.0,NaN,NaN,Cincinnati Bengals,1.0,9.0
3,Kalon Barnes,2022,CB,Baylor,72.0,183.0,4.23,NaN,NaN,NaN,NaN,NaN,Carolina Panthers,7.0,242.0
4,Chris Johnson,2008,RB,East Carolina,71.0,197.0,4.24,35.0,NaN,130.0,NaN,NaN,Tennessee Titans,1.0,24.0
5,Dri Archer,2014,WR,Kent State,68.0,173.0,4.26,38.0,20.0,122.0,6.86,4.06,Pittsburgh Steelers,3.0,97.0
6,Tariq Woolen,2022,CB,Texas-San Antonio,76.0,205.0,4.26,42.0,NaN,NaN,NaN,NaN,Seattle Seahawks,5.0,153.0
7,DJ Turner,2023,CB,Michigan,71.0,178.0,4.26,38.5,NaN,131.0,NaN,NaN,Cincinnati Bengals,2.0,60.0
8,Stanford Routt,2005,CB,Houston,73.0,193.0,4.27,36.5,NaN,129.0,6.63,3.90,Oakland Raiders,2.0,38.0
9,Marquise Goodwin,2013,WR,Texas,69.0,183.0,4.27,NaN,13.0,132.0,NaN,NaN,Buffalo Bills,3.0,78.0

## 10. Save the cleaned dataset

This is the main output from the notebook.

In [ ]:
combine_clean.to_csv("cleaned_combine_Data.csv", index=False)

print("Saved file: cleaned_combine_Data.csv")

Saved file: NFL_Combine_Data.csv

## Final note

This notebook intentionally keeps the cleaning light and readable.

It does **not**:
- create extra summary CSV files
- create derived columns like BMI
- group draft rounds into buckets
- remap real position labels into other positions

It focuses only on producing **one clean combine dataset** that can later be used in the master merge.